export type { StockRepository, StockValidationIssue, StockValidationResult } from './types'
export { createDefaultStockRepository } from './createStockRepository'
export { ImaginaPruebaStockRepository, mapStockRowToUnidad, PROYECTO_IMAGINA } from './imaginaPruebaRepository'
export { unidadSupabaseToDatosPropiedad } from './mapToDatosPropiedad'
export type { MapUnidadToPropiedadOptions } from './mapToDatosPropiedad'
export { validateUnidadSupabaseForMotor } from './validateStockInputs'
